from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BankRegistration(object):
    def setupUi(self, BankRegistration):
        BankRegistration.setObjectName("BankRegistration")
        BankRegistration.resize(300, 800)
        BankRegistration.setMinimumSize(QtCore.QSize(300, 300))
        BankRegistration.setMaximumSize(QtCore.QSize(300, 800))
        self.centralwidget = QtWidgets.QWidget(parent=BankRegistration)
        self.centralwidget.setObjectName("centralwidget")
        self.header_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.header_label.setGeometry(QtCore.QRect(60, 10, 161, 16))
        self.header_label.setObjectName("header_label")
        self.radioButton_log_in = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_log_in.setGeometry(QtCore.QRect(180, 30, 71, 20))
        self.radioButton_log_in.setObjectName("radioButton_log_in")
        self.radioButton_account_create = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_account_create.setGeometry(QtCore.QRect(30, 30, 121, 20))
        self.radioButton_account_create.setObjectName("radioButton_account_create")
        self.enter_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.enter_button.setGeometry(QtCore.QRect(80, 50, 113, 32))
        self.enter_button.setObjectName("enter_button")
        self.frame1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(10, 80, 280, 251))
        self.frame1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame1.setObjectName("frame1")
        self.name_label = QtWidgets.QLabel(parent=self.frame1)
        self.name_label.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.name_label.setObjectName("name_label")
        self.name_input = QtWidgets.QLineEdit(parent=self.frame1)
        self.name_input.setGeometry(QtCore.QRect(150, 20, 121, 15))
        self.name_input.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.name_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.name_input.setObjectName("name_input")
        self.age_account_number_label = QtWidgets.QLabel(parent=self.frame1)
        self.age_account_number_label.setGeometry(QtCore.QRect(10, 40, 151, 16))
        self.age_account_number_label.setObjectName("age_account_number_label")
        self.age_ccount_number_input = QtWidgets.QLineEdit(parent=self.frame1)
        self.age_ccount_number_input.setGeometry(QtCore.QRect(150, 40, 121, 15))
        self.age_ccount_number_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.age_ccount_number_input.setObjectName("age_ccount_number_input")
        self.address_label = QtWidgets.QLabel(parent=self.frame1)
        self.address_label.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.address_label.setObjectName("address_label")
        self.pin_label = QtWidgets.QLabel(parent=self.frame1)
        self.pin_label.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.pin_label.setObjectName("pin_label")
        self.set_balance_label = QtWidgets.QLabel(parent=self.frame1)
        self.set_balance_label.setGeometry(QtCore.QRect(10, 100, 81, 16))
        self.set_balance_label.setObjectName("set_balance_label")
        self.address_input = QtWidgets.QLineEdit(parent=self.frame1)
        self.address_input.setGeometry(QtCore.QRect(150, 60, 121, 15))
        self.address_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.address_input.setObjectName("address_input")
        self.pin_input = QtWidgets.QLineEdit(parent=self.frame1)
        self.pin_input.setGeometry(QtCore.QRect(150, 80, 121, 15))
        self.pin_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pin_input.setObjectName("pin_input")
        self.set_balance_input = QtWidgets.QLineEdit(parent=self.frame1)
        self.set_balance_input.setGeometry(QtCore.QRect(150, 100, 121, 15))
        self.set_balance_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.set_balance_input.setObjectName("set_balance_input")
        self.welcome_label = QtWidgets.QLabel(parent=self.frame1)
        self.welcome_label.setGeometry(QtCore.QRect(10, 120, 261, 71))
        self.welcome_label.setText("")
        self.welcome_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.welcome_label.setWordWrap(True)
        self.welcome_label.setObjectName("welcome_label")
        self.create_login = QtWidgets.QPushButton(parent=self.frame1)
        self.create_login.setGeometry(QtCore.QRect(60, 200, 161, 32))
        self.create_login.setObjectName("create_login")
        self.frame2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame2.setGeometry(QtCore.QRect(10, 340, 281, 101))
        self.frame2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame2.setObjectName("frame2")
        self.select_trans_label = QtWidgets.QLabel(parent=self.frame2)
        self.select_trans_label.setGeometry(QtCore.QRect(50, 0, 161, 31))
        self.select_trans_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_trans_label.setObjectName("select_trans_label")
        self.radioButton_deposit = QtWidgets.QRadioButton(parent=self.frame2)
        self.radioButton_deposit.setGeometry(QtCore.QRect(0, 30, 71, 20))
        self.radioButton_deposit.setObjectName("radioButton_deposit")
        self.radioButton_withdraw = QtWidgets.QRadioButton(parent=self.frame2)
        self.radioButton_withdraw.setGeometry(QtCore.QRect(80, 30, 81, 20))
        self.radioButton_withdraw.setObjectName("radioButton_withdraw")
        self.submit_button = QtWidgets.QPushButton(parent=self.frame2)
        self.submit_button.setGeometry(QtCore.QRect(80, 60, 113, 32))
        self.submit_button.setObjectName("submit_button")
        self.radioButton_balance = QtWidgets.QRadioButton(parent=self.frame2)
        self.radioButton_balance.setGeometry(QtCore.QRect(170, 30, 100, 20))
        self.radioButton_balance.setObjectName("radioButton_balance")
        self.frame3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame3.setGeometry(QtCore.QRect(10, 450, 281, 241))
        self.frame3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame3.setObjectName("frame3")
        self.trans_type_label = QtWidgets.QLabel(parent=self.frame3)
        self.trans_type_label.setGeometry(QtCore.QRect(10, 10, 111, 51))
        self.trans_type_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.trans_type_label.setObjectName("trans_type_label")
        self.input_trans_amount = QtWidgets.QLineEdit(parent=self.frame3)
        self.input_trans_amount.setGeometry(QtCore.QRect(140, 10, 113, 21))
        self.input_trans_amount.setObjectName("input_trans_amount")
        self.complete_button = QtWidgets.QPushButton(parent=self.frame3)
        self.complete_button.setGeometry(QtCore.QRect(50, 70, 161, 32))
        self.complete_button.setObjectName("complete_button")
        self.available_balance_label = QtWidgets.QLabel(parent=self.frame3)
        self.available_balance_label.setGeometry(QtCore.QRect(10, 110, 231, 51))
        self.available_balance_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.available_balance_label.setWordWrap(True)
        self.available_balance_label.setObjectName("available_balance_label")
        self.logout_button = QtWidgets.QPushButton(parent=self.frame3)
        self.logout_button.setGeometry(QtCore.QRect(80, 190, 113, 32))
        self.logout_button.setObjectName("logout_button")
        BankRegistration.setCentralWidget(self.centralwidget)
        self.menu_bar = QtWidgets.QMenuBar(parent=BankRegistration)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 300, 37))
        self.menu_bar.setObjectName("menu_bar")
        BankRegistration.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(parent=BankRegistration)
        self.status_bar.setObjectName("status_bar")
        BankRegistration.setStatusBar(self.status_bar)

        self.retranslateUi(BankRegistration)
        QtCore.QMetaObject.connectSlotsByName(BankRegistration)

    def retranslateUi(self, BankRegistration):
        _translate = QtCore.QCoreApplication.translate
        BankRegistration.setWindowTitle(_translate("BankRegistration", "G&M Banking"))
        self.header_label.setText(_translate("BankRegistration", "Welcome to G&M Banking"))
        self.radioButton_log_in.setText(_translate("BankRegistration", "Login"))
        self.radioButton_account_create.setText(_translate("BankRegistration", "Create Account"))
        self.enter_button.setText(_translate("BankRegistration", "Enter"))
        self.name_label.setText(_translate("BankRegistration", "Name:"))
        self.age_account_number_label.setText(_translate("BankRegistration", "Age:"))
        self.address_label.setText(_translate("BankRegistration", "Address:"))
        self.pin_label.setText(_translate("BankRegistration", "Pin:"))
        self.set_balance_label.setText(_translate("BankRegistration", "Set Your Balance:"))
        self.create_login.setText(_translate("BankRegistration", "Login"))
        self.select_trans_label.setText(_translate("BankRegistration", "Select Transaction Type"))
        self.radioButton_deposit.setText(_translate("BankRegistration", "Deposit"))
        self.radioButton_withdraw.setText(_translate("BankRegistration", "Withdraw"))
        self.submit_button.setText(_translate("BankRegistration", "Submit"))
        self.radioButton_balance.setText(_translate("BankRegistration", "Your Balance"))
        self.trans_type_label.setText(_translate("BankRegistration", "transaction type"))
        self.complete_button.setText(_translate("BankRegistration", "Complete Transaction"))
        self.available_balance_label.setText(_translate("BankRegistration", "Available Balance:"))
        self.logout_button.setText(_translate("BankRegistration", "Logout"))
